### ISSUE TITLE
Liveseo has nice stuff

### ISSUE THREAD

**Issue by guci0** [vulcandigital/silverstripe-seo#18]
googlesuggestfield.js – I think it's ideal for "set keyword focus". Some kind a stars / points – also will be nice.

EDIT: After change Title and publish – 'Search Preview' needs to be refreshed to see changes (F5).

**Comment by zanderwar** [comment]
It already refreshes on save, whether published or not, but I agree with you that it'd be better to have the analysis lives just need to figure out a way to make it very simple for developers to contribute, as the best sales point of this module is the ability to create your own analyses very easily
