### ISSUE TITLE
Module makes new pages un-editable

### ISSUE THREAD

**Issue by jonom** [vulcandigital/silverstripe-seo#28]
As reported in https://github.com/vulcandigital/silverstripe-seo/pull/27 new pages will return a 404 error to the `getRenderedHtml()` method. For me this made new pages inaccessible in the CMS.

**Comment by zanderwar** [comment]
Sorry for the major delay, I have merged #27 in and it's currently in dev-master, will get a release out soon

**Comment by zanderwar** [comment]
See #33 for new issue spawned from this fix
