### ISSUE TITLE
file_get_contents error

### ISSUE THREAD

**Issue by Valandur** [vulcandigital/silverstripe-seo#34]
SilverStripe: 4.1.2
silverstripe-seo: 1.0.1

I get the following error when trying to view a page:

`[Warning] file_get_contents(): php_network_getaddresses: getaddrinfo failed: Name or service not known`

This is probably due to the fact that my website is running on `project.localhost`, and that name cannot be resolved since I don't have a hosts entry (Chrome forwards `*.localhost` domains to the localhost, so I don't need a hosts entry).

I believe it would also not work if my website was protected by basic auth, such as on a staging/test server, since there is no way of passing credentials.

It would be nice if there was a way to disable the health analysis, or pass additional options such as headers.

**Comment by zanderwar** [comment]
Hey thanks for bringing this up

I'll eventually get around to seeing what I can do here for you and at the very least providing a way to disable healthy analysis via YML may be quite ideal.

What headers would you consider passing to the Health Analysis?

**Comment by Valandur** [comment]
Well for basic auth only the `Authorization` header is required, but I guess a more general approach to allow arbitrary headers would make sense, unless this conflicts with some internally used headers

**Comment by zanderwar** [comment]
This should be resolved in the latest release as `file_get_contents` is no longer used, can you give it a shot and let me know if you have any issues? I'll close this for now
