### ISSUE TITLE
Not compatible with PHP 7.3 due to dependency of sunra/php-simple-html-dom-parser

### ISSUE THREAD

**Issue by obj63mc** [vulcandigital/silverstripe-seo#36]
Currently the composer module sunra/php-simple-html-dom-parser does not support php 7.3 https://github.com/sunra/php-simple-html-dom-parser/issues/64

It does not appear that module is supported anymore so wondering if we might have a way to work around this issue or have your module run a fork of this package.

**Comment by zanderwar** [comment]
Merged your PR, thank you.
