### ISSUE TITLE
server with request limit causes internal server error

### ISSUE THREAD

**Issue by guyvanbael** [vulcandigital/silverstripe-seo#38]
when deploying to a server which has a limit on requests (to prevent infinite loops), i get an internal server error.
`
file_get_contents(myUrl/?stage=Stage): failed to open stream: HTTP request failed! HTTP/1.0 429 Too Many Requests\r\n in myUrl/public_html/vendor/vulcandigital/silverstripe-seo/src/Extensions/PageHealthExtension.php 
`

**Comment by zanderwar** [comment]
Hi @guyvanbael 

I'm attempting to move this away entirely from making any HTTP requests at all, and instead using the built in renderer SilverStripe uses. I'm just lacking the time to do anything about it at the moment.

If I recall correctly however I do believe that this module only makes [one single request](https://github.com/vulcandigital/silverstripe-seo/blob/master/src/Extensions/PageHealthExtension.php#L60) when the preview loads, not dozens and definitely not enough to trigger rate limiting.
